# Generated by Django 2.2.5 on 2019-10-31 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='accuracy',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='cleanliness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='communication',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='location',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.IntegerField(),
        ),
    ]
